import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // `.claude/worktrees/*` holds git worktrees of this same repo, each with a
  // node_modules symlink back here. Without this, `eslint .` follows that
  // symlink and lints every dependency, which is where thousands of phantom
  // errors come from.
  {
    // Both of these are written by the Lovable agent and regenerated by it.
    // previewAuthStorage.ts was hand-formatted to satisfy prettier on 2026-08-24
    // and Lovable rewrote it in single quotes hours later, turning CI red on main
    // again. A file a generator owns cannot be kept formatted by hand.
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      ".claude",
      "src/integrations/supabase/types.ts",
      "src/integrations/supabase/previewAuthStorage.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  eslintPluginPrettier,
);
