/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthorityRouteImport } from './routes/authority'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as EssentialsRouteImport } from './routes/essentials'
import { Route as Ga4RouteImport } from './routes/ga4'
import { Route as GapsRouteImport } from './routes/gaps'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MeasurementRouteImport } from './routes/measurement'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as OpenaiAdsRouteImport } from './routes/openai-ads'
import { Route as OpenseoRouteImport } from './routes/openseo'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as SeoRunsRouteImport } from './routes/seo-runs'
import { Route as SpendRouteImport } from './routes/spend'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TodayRouteImport } from './routes/today'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdsIndexRouteImport } from './routes/ads.index'
import { Route as AdsAdvertisersRouteImport } from './routes/ads.advertisers'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as ApiAgentChatRouteImport } from './routes/api/agent-chat'
import { Route as ApiStudioChatRouteImport } from './routes/api/studio-chat'
import { Route as AssetsIndexRouteImport } from './routes/assets.index'
import { Route as AssetsIdRouteImport } from './routes/assets.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CapabilitiesIndexRouteImport } from './routes/capabilities.index'
import { Route as CapabilitiesIdRouteImport } from './routes/capabilities.$id'
import { Route as CapabilitiesSystemsRouteImport } from './routes/capabilities.systems'
import { Route as ChangesIndexRouteImport } from './routes/changes.index'
import { Route as ChangesIdRouteImport } from './routes/changes.$id'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgeIdRouteImport } from './routes/knowledge.$id'
import { Route as KnowledgeManualRouteImport } from './routes/knowledge.manual'
import { Route as PagesIndexRouteImport } from './routes/pages.index'
import { Route as PagesToolsRouteImport } from './routes/pages.tools'
import { Route as RecommendationsIndexRouteImport } from './routes/recommendations.index'
import { Route as RecommendationsIdRouteImport } from './routes/recommendations.$id'
import { Route as SchedulerIndexRouteImport } from './routes/scheduler.index'
import { Route as SchedulerIdRouteImport } from './routes/scheduler.$id'
import { Route as SearchIndexRouteImport } from './routes/search.index'
import { Route as SearchToolsRouteImport } from './routes/search.tools'
import { Route as SeoRunsIndexRouteImport } from './routes/seo-runs.index'
import { Route as SeoRunsIdRouteImport } from './routes/seo-runs.$id'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as WorkflowsIdRouteImport } from './routes/workflows.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as CapabilitiesSystemsIndexRouteImport } from './routes/capabilities.systems.index'
import { Route as CapabilitiesSystemsKeyRouteImport } from './routes/capabilities.systems.$key'
import { Route as ApiPublicHooksDataforseoPostbackRouteImport } from './routes/api/public/hooks/dataforseo-postback'
import { Route as ApiPublicHooksOpenaiAdsConversionsRouteImport } from './routes/api/public/hooks/openai-ads-conversions'
import { Route as ApiPublicHooksOpenaiAdsEventsRouteImport } from './routes/api/public/hooks/openai-ads-events'
import { Route as ApiPublicHooksProposeFromEvidenceRouteImport } from './routes/api/public/hooks/propose-from-evidence'
import { Route as ApiPublicHooksSchedulerTickRouteImport } from './routes/api/public/hooks/scheduler-tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityRoute = AuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const EssentialsRoute = EssentialsRouteImport.update({
  id: '/essentials',
  path: '/essentials',
  getParentRoute: () => rootRouteImport,
} as any)
const Ga4Route = Ga4RouteImport.update({
  id: '/ga4',
  path: '/ga4',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsRoute = GapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementRoute = MeasurementRouteImport.update({
  id: '/measurement',
  path: '/measurement',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenaiAdsRoute = OpenaiAdsRouteImport.update({
  id: '/openai-ads',
  path: '/openai-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenseoRoute = OpenseoRouteImport.update({
  id: '/openseo',
  path: '/openseo',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRunsRoute = SeoRunsRouteImport.update({
  id: '/seo-runs',
  path: '/seo-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendRoute = SpendRouteImport.update({
  id: '/spend',
  path: '/spend',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdsIndexRoute = AdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsAdvertisersRoute = AdsAdvertisersRouteImport.update({
  id: '/ads/advertisers',
  path: '/ads/advertisers',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const ApiAgentChatRoute = ApiAgentChatRouteImport.update({
  id: '/api/agent-chat',
  path: '/api/agent-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudioChatRoute = ApiStudioChatRouteImport.update({
  id: '/api/studio-chat',
  path: '/api/studio-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsIdRoute = AssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssetsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const CapabilitiesIndexRoute = CapabilitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CapabilitiesRoute,
} as any)
const CapabilitiesIdRoute = CapabilitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CapabilitiesRoute,
} as any)
const CapabilitiesSystemsRoute = CapabilitiesSystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => CapabilitiesRoute,
} as any)
const ChangesIndexRoute = ChangesIndexRouteImport.update({
  id: '/changes/',
  path: '/changes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesIdRoute = ChangesIdRouteImport.update({
  id: '/changes/$id',
  path: '/changes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeIdRoute = KnowledgeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeManualRoute = KnowledgeManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => KnowledgeRoute,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesToolsRoute = PagesToolsRouteImport.update({
  id: '/pages/tools',
  path: '/pages/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsIndexRoute = RecommendationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecommendationsRoute,
} as any)
const RecommendationsIdRoute = RecommendationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecommendationsRoute,
} as any)
const SchedulerIndexRoute = SchedulerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchedulerRoute,
} as any)
const SchedulerIdRoute = SchedulerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SchedulerRoute,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchToolsRoute = SearchToolsRouteImport.update({
  id: '/search/tools',
  path: '/search/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRunsIndexRoute = SeoRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeoRunsRoute,
} as any)
const SeoRunsIdRoute = SeoRunsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SeoRunsRoute,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkflowsRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const CapabilitiesSystemsIndexRoute =
  CapabilitiesSystemsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CapabilitiesSystemsRoute,
  } as any)
const CapabilitiesSystemsKeyRoute = CapabilitiesSystemsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => CapabilitiesSystemsRoute,
} as any)
const ApiPublicHooksDataforseoPostbackRoute =
  ApiPublicHooksDataforseoPostbackRouteImport.update({
    id: '/api/public/hooks/dataforseo-postback',
    path: '/api/public/hooks/dataforseo-postback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOpenaiAdsConversionsRoute =
  ApiPublicHooksOpenaiAdsConversionsRouteImport.update({
    id: '/api/public/hooks/openai-ads-conversions',
    path: '/api/public/hooks/openai-ads-conversions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOpenaiAdsEventsRoute =
  ApiPublicHooksOpenaiAdsEventsRouteImport.update({
    id: '/api/public/hooks/openai-ads-events',
    path: '/api/public/hooks/openai-ads-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProposeFromEvidenceRoute =
  ApiPublicHooksProposeFromEvidenceRouteImport.update({
    id: '/api/public/hooks/propose-from-evidence',
    path: '/api/public/hooks/propose-from-evidence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSchedulerTickRoute =
  ApiPublicHooksSchedulerTickRouteImport.update({
    id: '/api/public/hooks/scheduler-tick',
    path: '/api/public/hooks/scheduler-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/ask': typeof AskRoute
  '/assets': typeof AssetsRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/authority': typeof AuthorityRoute
  '/capabilities': typeof CapabilitiesRouteWithChildren
  '/command-center': typeof CommandCenterRoute
  '/competitors': typeof CompetitorsRoute
  '/essentials': typeof EssentialsRoute
  '/ga4': typeof Ga4Route
  '/gaps': typeof GapsRoute
  '/keywords': typeof KeywordsRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/mcp': typeof McpRoute
  '/measurement': typeof MeasurementRoute
  '/notes': typeof NotesRoute
  '/openai-ads': typeof OpenaiAdsRoute
  '/openseo': typeof OpenseoRoute
  '/operators': typeof OperatorsRoute
  '/recommendations': typeof RecommendationsRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/scheduler': typeof SchedulerRouteWithChildren
  '/seo-runs': typeof SeoRunsRouteWithChildren
  '/spend': typeof SpendRoute
  '/studio': typeof StudioRoute
  '/today': typeof TodayRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ads/advertisers': typeof AdsAdvertisersRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/agent-chat': typeof ApiAgentChatRoute
  '/api/studio-chat': typeof ApiStudioChatRoute
  '/assets/$id': typeof AssetsIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/capabilities/$id': typeof CapabilitiesIdRoute
  '/capabilities/systems': typeof CapabilitiesSystemsRouteWithChildren
  '/changes/$id': typeof ChangesIdRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/knowledge/manual': typeof KnowledgeManualRoute
  '/pages/tools': typeof PagesToolsRoute
  '/recommendations/$id': typeof RecommendationsIdRoute
  '/scheduler/$id': typeof SchedulerIdRoute
  '/search/tools': typeof SearchToolsRoute
  '/seo-runs/$id': typeof SeoRunsIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/ads/': typeof AdsIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/assets/': typeof AssetsIndexRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
  '/changes/': typeof ChangesIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/pages/': typeof PagesIndexRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/scheduler/': typeof SchedulerIndexRoute
  '/search/': typeof SearchIndexRoute
  '/seo-runs/': typeof SeoRunsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/capabilities/systems/$key': typeof CapabilitiesSystemsKeyRoute
  '/capabilities/systems/': typeof CapabilitiesSystemsIndexRoute
  '/api/public/hooks/dataforseo-postback': typeof ApiPublicHooksDataforseoPostbackRoute
  '/api/public/hooks/openai-ads-conversions': typeof ApiPublicHooksOpenaiAdsConversionsRoute
  '/api/public/hooks/openai-ads-events': typeof ApiPublicHooksOpenaiAdsEventsRoute
  '/api/public/hooks/propose-from-evidence': typeof ApiPublicHooksProposeFromEvidenceRoute
  '/api/public/hooks/scheduler-tick': typeof ApiPublicHooksSchedulerTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/approvals': typeof ApprovalsRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRouteWithChildren
  '/authority': typeof AuthorityRoute
  '/command-center': typeof CommandCenterRoute
  '/competitors': typeof CompetitorsRoute
  '/essentials': typeof EssentialsRoute
  '/ga4': typeof Ga4Route
  '/gaps': typeof GapsRoute
  '/keywords': typeof KeywordsRoute
  '/mcp': typeof McpRoute
  '/measurement': typeof MeasurementRoute
  '/notes': typeof NotesRoute
  '/openai-ads': typeof OpenaiAdsRoute
  '/openseo': typeof OpenseoRoute
  '/operators': typeof OperatorsRoute
  '/roadmap': typeof RoadmapRoute
  '/spend': typeof SpendRoute
  '/studio': typeof StudioRoute
  '/today': typeof TodayRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ads/advertisers': typeof AdsAdvertisersRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/agent-chat': typeof ApiAgentChatRoute
  '/api/studio-chat': typeof ApiStudioChatRoute
  '/assets/$id': typeof AssetsIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/capabilities/$id': typeof CapabilitiesIdRoute
  '/changes/$id': typeof ChangesIdRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/knowledge/manual': typeof KnowledgeManualRoute
  '/pages/tools': typeof PagesToolsRoute
  '/recommendations/$id': typeof RecommendationsIdRoute
  '/scheduler/$id': typeof SchedulerIdRoute
  '/search/tools': typeof SearchToolsRoute
  '/seo-runs/$id': typeof SeoRunsIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/ads': typeof AdsIndexRoute
  '/agents': typeof AgentsIndexRoute
  '/assets': typeof AssetsIndexRoute
  '/capabilities': typeof CapabilitiesIndexRoute
  '/changes': typeof ChangesIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/pages': typeof PagesIndexRoute
  '/recommendations': typeof RecommendationsIndexRoute
  '/scheduler': typeof SchedulerIndexRoute
  '/search': typeof SearchIndexRoute
  '/seo-runs': typeof SeoRunsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/capabilities/systems/$key': typeof CapabilitiesSystemsKeyRoute
  '/capabilities/systems': typeof CapabilitiesSystemsIndexRoute
  '/api/public/hooks/dataforseo-postback': typeof ApiPublicHooksDataforseoPostbackRoute
  '/api/public/hooks/openai-ads-conversions': typeof ApiPublicHooksOpenaiAdsConversionsRoute
  '/api/public/hooks/openai-ads-events': typeof ApiPublicHooksOpenaiAdsEventsRoute
  '/api/public/hooks/propose-from-evidence': typeof ApiPublicHooksProposeFromEvidenceRoute
  '/api/public/hooks/scheduler-tick': typeof ApiPublicHooksSchedulerTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/ask': typeof AskRoute
  '/assets': typeof AssetsRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/authority': typeof AuthorityRoute
  '/capabilities': typeof CapabilitiesRouteWithChildren
  '/command-center': typeof CommandCenterRoute
  '/competitors': typeof CompetitorsRoute
  '/essentials': typeof EssentialsRoute
  '/ga4': typeof Ga4Route
  '/gaps': typeof GapsRoute
  '/keywords': typeof KeywordsRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/mcp': typeof McpRoute
  '/measurement': typeof MeasurementRoute
  '/notes': typeof NotesRoute
  '/openai-ads': typeof OpenaiAdsRoute
  '/openseo': typeof OpenseoRoute
  '/operators': typeof OperatorsRoute
  '/recommendations': typeof RecommendationsRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/scheduler': typeof SchedulerRouteWithChildren
  '/seo-runs': typeof SeoRunsRouteWithChildren
  '/spend': typeof SpendRoute
  '/studio': typeof StudioRoute
  '/today': typeof TodayRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ads/advertisers': typeof AdsAdvertisersRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/agent-chat': typeof ApiAgentChatRoute
  '/api/studio-chat': typeof ApiStudioChatRoute
  '/assets/$id': typeof AssetsIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/capabilities/$id': typeof CapabilitiesIdRoute
  '/capabilities/systems': typeof CapabilitiesSystemsRouteWithChildren
  '/changes/$id': typeof ChangesIdRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/knowledge/manual': typeof KnowledgeManualRoute
  '/pages/tools': typeof PagesToolsRoute
  '/recommendations/$id': typeof RecommendationsIdRoute
  '/scheduler/$id': typeof SchedulerIdRoute
  '/search/tools': typeof SearchToolsRoute
  '/seo-runs/$id': typeof SeoRunsIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/ads/': typeof AdsIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/assets/': typeof AssetsIndexRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
  '/changes/': typeof ChangesIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/pages/': typeof PagesIndexRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/scheduler/': typeof SchedulerIndexRoute
  '/search/': typeof SearchIndexRoute
  '/seo-runs/': typeof SeoRunsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/capabilities/systems/$key': typeof CapabilitiesSystemsKeyRoute
  '/capabilities/systems/': typeof CapabilitiesSystemsIndexRoute
  '/api/public/hooks/dataforseo-postback': typeof ApiPublicHooksDataforseoPostbackRoute
  '/api/public/hooks/openai-ads-conversions': typeof ApiPublicHooksOpenaiAdsConversionsRoute
  '/api/public/hooks/openai-ads-events': typeof ApiPublicHooksOpenaiAdsEventsRoute
  '/api/public/hooks/propose-from-evidence': typeof ApiPublicHooksProposeFromEvidenceRoute
  '/api/public/hooks/scheduler-tick': typeof ApiPublicHooksSchedulerTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/agents'
    | '/approvals'
    | '/ask'
    | '/assets'
    | '/auth'
    | '/authority'
    | '/capabilities'
    | '/command-center'
    | '/competitors'
    | '/essentials'
    | '/ga4'
    | '/gaps'
    | '/keywords'
    | '/knowledge'
    | '/mcp'
    | '/measurement'
    | '/notes'
    | '/openai-ads'
    | '/openseo'
    | '/operators'
    | '/recommendations'
    | '/roadmap'
    | '/scheduler'
    | '/seo-runs'
    | '/spend'
    | '/studio'
    | '/today'
    | '/workflows'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ads/advertisers'
    | '/agents/$id'
    | '/api/agent-chat'
    | '/api/studio-chat'
    | '/assets/$id'
    | '/auth/callback'
    | '/capabilities/$id'
    | '/capabilities/systems'
    | '/changes/$id'
    | '/knowledge/$id'
    | '/knowledge/manual'
    | '/pages/tools'
    | '/recommendations/$id'
    | '/scheduler/$id'
    | '/search/tools'
    | '/seo-runs/$id'
    | '/workflows/$id'
    | '/ads/'
    | '/agents/'
    | '/assets/'
    | '/capabilities/'
    | '/changes/'
    | '/knowledge/'
    | '/pages/'
    | '/recommendations/'
    | '/scheduler/'
    | '/search/'
    | '/seo-runs/'
    | '/workflows/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/capabilities/systems/$key'
    | '/capabilities/systems/'
    | '/api/public/hooks/dataforseo-postback'
    | '/api/public/hooks/openai-ads-conversions'
    | '/api/public/hooks/openai-ads-events'
    | '/api/public/hooks/propose-from-evidence'
    | '/api/public/hooks/scheduler-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/approvals'
    | '/ask'
    | '/auth'
    | '/authority'
    | '/command-center'
    | '/competitors'
    | '/essentials'
    | '/ga4'
    | '/gaps'
    | '/keywords'
    | '/mcp'
    | '/measurement'
    | '/notes'
    | '/openai-ads'
    | '/openseo'
    | '/operators'
    | '/roadmap'
    | '/spend'
    | '/studio'
    | '/today'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ads/advertisers'
    | '/agents/$id'
    | '/api/agent-chat'
    | '/api/studio-chat'
    | '/assets/$id'
    | '/auth/callback'
    | '/capabilities/$id'
    | '/changes/$id'
    | '/knowledge/$id'
    | '/knowledge/manual'
    | '/pages/tools'
    | '/recommendations/$id'
    | '/scheduler/$id'
    | '/search/tools'
    | '/seo-runs/$id'
    | '/workflows/$id'
    | '/ads'
    | '/agents'
    | '/assets'
    | '/capabilities'
    | '/changes'
    | '/knowledge'
    | '/pages'
    | '/recommendations'
    | '/scheduler'
    | '/search'
    | '/seo-runs'
    | '/workflows'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/capabilities/systems/$key'
    | '/capabilities/systems'
    | '/api/public/hooks/dataforseo-postback'
    | '/api/public/hooks/openai-ads-conversions'
    | '/api/public/hooks/openai-ads-events'
    | '/api/public/hooks/propose-from-evidence'
    | '/api/public/hooks/scheduler-tick'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/agents'
    | '/approvals'
    | '/ask'
    | '/assets'
    | '/auth'
    | '/authority'
    | '/capabilities'
    | '/command-center'
    | '/competitors'
    | '/essentials'
    | '/ga4'
    | '/gaps'
    | '/keywords'
    | '/knowledge'
    | '/mcp'
    | '/measurement'
    | '/notes'
    | '/openai-ads'
    | '/openseo'
    | '/operators'
    | '/recommendations'
    | '/roadmap'
    | '/scheduler'
    | '/seo-runs'
    | '/spend'
    | '/studio'
    | '/today'
    | '/workflows'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ads/advertisers'
    | '/agents/$id'
    | '/api/agent-chat'
    | '/api/studio-chat'
    | '/assets/$id'
    | '/auth/callback'
    | '/capabilities/$id'
    | '/capabilities/systems'
    | '/changes/$id'
    | '/knowledge/$id'
    | '/knowledge/manual'
    | '/pages/tools'
    | '/recommendations/$id'
    | '/scheduler/$id'
    | '/search/tools'
    | '/seo-runs/$id'
    | '/workflows/$id'
    | '/ads/'
    | '/agents/'
    | '/assets/'
    | '/capabilities/'
    | '/changes/'
    | '/knowledge/'
    | '/pages/'
    | '/recommendations/'
    | '/scheduler/'
    | '/search/'
    | '/seo-runs/'
    | '/workflows/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/capabilities/systems/$key'
    | '/capabilities/systems/'
    | '/api/public/hooks/dataforseo-postback'
    | '/api/public/hooks/openai-ads-conversions'
    | '/api/public/hooks/openai-ads-events'
    | '/api/public/hooks/propose-from-evidence'
    | '/api/public/hooks/scheduler-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ApprovalsRoute: typeof ApprovalsRoute
  AskRoute: typeof AskRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AuthorityRoute: typeof AuthorityRoute
  CapabilitiesRoute: typeof CapabilitiesRouteWithChildren
  CommandCenterRoute: typeof CommandCenterRoute
  CompetitorsRoute: typeof CompetitorsRoute
  EssentialsRoute: typeof EssentialsRoute
  Ga4Route: typeof Ga4Route
  GapsRoute: typeof GapsRoute
  KeywordsRoute: typeof KeywordsRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  McpRoute: typeof McpRoute
  MeasurementRoute: typeof MeasurementRoute
  NotesRoute: typeof NotesRoute
  OpenaiAdsRoute: typeof OpenaiAdsRoute
  OpenseoRoute: typeof OpenseoRoute
  OperatorsRoute: typeof OperatorsRoute
  RecommendationsRoute: typeof RecommendationsRouteWithChildren
  RoadmapRoute: typeof RoadmapRoute
  SchedulerRoute: typeof SchedulerRouteWithChildren
  SeoRunsRoute: typeof SeoRunsRouteWithChildren
  SpendRoute: typeof SpendRoute
  StudioRoute: typeof StudioRoute
  TodayRoute: typeof TodayRoute
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdsAdvertisersRoute: typeof AdsAdvertisersRoute
  ApiAgentChatRoute: typeof ApiAgentChatRoute
  ApiStudioChatRoute: typeof ApiStudioChatRoute
  ChangesIdRoute: typeof ChangesIdRoute
  PagesToolsRoute: typeof PagesToolsRoute
  SearchToolsRoute: typeof SearchToolsRoute
  AdsIndexRoute: typeof AdsIndexRoute
  ChangesIndexRoute: typeof ChangesIndexRoute
  PagesIndexRoute: typeof PagesIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksDataforseoPostbackRoute: typeof ApiPublicHooksDataforseoPostbackRoute
  ApiPublicHooksOpenaiAdsConversionsRoute: typeof ApiPublicHooksOpenaiAdsConversionsRoute
  ApiPublicHooksOpenaiAdsEventsRoute: typeof ApiPublicHooksOpenaiAdsEventsRoute
  ApiPublicHooksProposeFromEvidenceRoute: typeof ApiPublicHooksProposeFromEvidenceRoute
  ApiPublicHooksSchedulerTickRoute: typeof ApiPublicHooksSchedulerTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority': {
      id: '/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essentials': {
      id: '/essentials'
      path: '/essentials'
      fullPath: '/essentials'
      preLoaderRoute: typeof EssentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga4': {
      id: '/ga4'
      path: '/ga4'
      fullPath: '/ga4'
      preLoaderRoute: typeof Ga4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps': {
      id: '/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof GapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurement': {
      id: '/measurement'
      path: '/measurement'
      fullPath: '/measurement'
      preLoaderRoute: typeof MeasurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openai-ads': {
      id: '/openai-ads'
      path: '/openai-ads'
      fullPath: '/openai-ads'
      preLoaderRoute: typeof OpenaiAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openseo': {
      id: '/openseo'
      path: '/openseo'
      fullPath: '/openseo'
      preLoaderRoute: typeof OpenseoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-runs': {
      id: '/seo-runs'
      path: '/seo-runs'
      fullPath: '/seo-runs'
      preLoaderRoute: typeof SeoRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spend': {
      id: '/spend'
      path: '/spend'
      fullPath: '/spend'
      preLoaderRoute: typeof SpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/': {
      id: '/ads/'
      path: '/ads'
      fullPath: '/ads/'
      preLoaderRoute: typeof AdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/advertisers': {
      id: '/ads/advertisers'
      path: '/ads/advertisers'
      fullPath: '/ads/advertisers'
      preLoaderRoute: typeof AdsAdvertisersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/api/agent-chat': {
      id: '/api/agent-chat'
      path: '/api/agent-chat'
      fullPath: '/api/agent-chat'
      preLoaderRoute: typeof ApiAgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/studio-chat': {
      id: '/api/studio-chat'
      path: '/api/studio-chat'
      fullPath: '/api/studio-chat'
      preLoaderRoute: typeof ApiStudioChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/$id': {
      id: '/assets/$id'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AssetsIdRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/capabilities/': {
      id: '/capabilities/'
      path: '/'
      fullPath: '/capabilities/'
      preLoaderRoute: typeof CapabilitiesIndexRouteImport
      parentRoute: typeof CapabilitiesRoute
    }
    '/capabilities/$id': {
      id: '/capabilities/$id'
      path: '/$id'
      fullPath: '/capabilities/$id'
      preLoaderRoute: typeof CapabilitiesIdRouteImport
      parentRoute: typeof CapabilitiesRoute
    }
    '/capabilities/systems': {
      id: '/capabilities/systems'
      path: '/systems'
      fullPath: '/capabilities/systems'
      preLoaderRoute: typeof CapabilitiesSystemsRouteImport
      parentRoute: typeof CapabilitiesRoute
    }
    '/changes/': {
      id: '/changes/'
      path: '/changes'
      fullPath: '/changes/'
      preLoaderRoute: typeof ChangesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes/$id': {
      id: '/changes/$id'
      path: '/changes/$id'
      fullPath: '/changes/$id'
      preLoaderRoute: typeof ChangesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/$id': {
      id: '/knowledge/$id'
      path: '/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof KnowledgeIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/manual': {
      id: '/knowledge/manual'
      path: '/manual'
      fullPath: '/knowledge/manual'
      preLoaderRoute: typeof KnowledgeManualRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/pages/': {
      id: '/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/tools': {
      id: '/pages/tools'
      path: '/pages/tools'
      fullPath: '/pages/tools'
      preLoaderRoute: typeof PagesToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations/': {
      id: '/recommendations/'
      path: '/'
      fullPath: '/recommendations/'
      preLoaderRoute: typeof RecommendationsIndexRouteImport
      parentRoute: typeof RecommendationsRoute
    }
    '/recommendations/$id': {
      id: '/recommendations/$id'
      path: '/$id'
      fullPath: '/recommendations/$id'
      preLoaderRoute: typeof RecommendationsIdRouteImport
      parentRoute: typeof RecommendationsRoute
    }
    '/scheduler/': {
      id: '/scheduler/'
      path: '/'
      fullPath: '/scheduler/'
      preLoaderRoute: typeof SchedulerIndexRouteImport
      parentRoute: typeof SchedulerRoute
    }
    '/scheduler/$id': {
      id: '/scheduler/$id'
      path: '/$id'
      fullPath: '/scheduler/$id'
      preLoaderRoute: typeof SchedulerIdRouteImport
      parentRoute: typeof SchedulerRoute
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/tools': {
      id: '/search/tools'
      path: '/search/tools'
      fullPath: '/search/tools'
      preLoaderRoute: typeof SearchToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-runs/': {
      id: '/seo-runs/'
      path: '/'
      fullPath: '/seo-runs/'
      preLoaderRoute: typeof SeoRunsIndexRouteImport
      parentRoute: typeof SeoRunsRoute
    }
    '/seo-runs/$id': {
      id: '/seo-runs/$id'
      path: '/$id'
      fullPath: '/seo-runs/$id'
      preLoaderRoute: typeof SeoRunsIdRouteImport
      parentRoute: typeof SeoRunsRoute
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/$id': {
      id: '/workflows/$id'
      path: '/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/systems/': {
      id: '/capabilities/systems/'
      path: '/'
      fullPath: '/capabilities/systems/'
      preLoaderRoute: typeof CapabilitiesSystemsIndexRouteImport
      parentRoute: typeof CapabilitiesSystemsRoute
    }
    '/capabilities/systems/$key': {
      id: '/capabilities/systems/$key'
      path: '/$key'
      fullPath: '/capabilities/systems/$key'
      preLoaderRoute: typeof CapabilitiesSystemsKeyRouteImport
      parentRoute: typeof CapabilitiesSystemsRoute
    }
    '/api/public/hooks/dataforseo-postback': {
      id: '/api/public/hooks/dataforseo-postback'
      path: '/api/public/hooks/dataforseo-postback'
      fullPath: '/api/public/hooks/dataforseo-postback'
      preLoaderRoute: typeof ApiPublicHooksDataforseoPostbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/openai-ads-conversions': {
      id: '/api/public/hooks/openai-ads-conversions'
      path: '/api/public/hooks/openai-ads-conversions'
      fullPath: '/api/public/hooks/openai-ads-conversions'
      preLoaderRoute: typeof ApiPublicHooksOpenaiAdsConversionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/openai-ads-events': {
      id: '/api/public/hooks/openai-ads-events'
      path: '/api/public/hooks/openai-ads-events'
      fullPath: '/api/public/hooks/openai-ads-events'
      preLoaderRoute: typeof ApiPublicHooksOpenaiAdsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/propose-from-evidence': {
      id: '/api/public/hooks/propose-from-evidence'
      path: '/api/public/hooks/propose-from-evidence'
      fullPath: '/api/public/hooks/propose-from-evidence'
      preLoaderRoute: typeof ApiPublicHooksProposeFromEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scheduler-tick': {
      id: '/api/public/hooks/scheduler-tick'
      path: '/api/public/hooks/scheduler-tick'
      fullPath: '/api/public/hooks/scheduler-tick'
      preLoaderRoute: typeof ApiPublicHooksSchedulerTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface AssetsRouteChildren {
  AssetsIdRoute: typeof AssetsIdRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsIdRoute: AssetsIdRoute,
  AssetsIndexRoute: AssetsIndexRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CapabilitiesSystemsRouteChildren {
  CapabilitiesSystemsKeyRoute: typeof CapabilitiesSystemsKeyRoute
  CapabilitiesSystemsIndexRoute: typeof CapabilitiesSystemsIndexRoute
}

const CapabilitiesSystemsRouteChildren: CapabilitiesSystemsRouteChildren = {
  CapabilitiesSystemsKeyRoute: CapabilitiesSystemsKeyRoute,
  CapabilitiesSystemsIndexRoute: CapabilitiesSystemsIndexRoute,
}

const CapabilitiesSystemsRouteWithChildren =
  CapabilitiesSystemsRoute._addFileChildren(CapabilitiesSystemsRouteChildren)

interface CapabilitiesRouteChildren {
  CapabilitiesIdRoute: typeof CapabilitiesIdRoute
  CapabilitiesSystemsRoute: typeof CapabilitiesSystemsRouteWithChildren
  CapabilitiesIndexRoute: typeof CapabilitiesIndexRoute
}

const CapabilitiesRouteChildren: CapabilitiesRouteChildren = {
  CapabilitiesIdRoute: CapabilitiesIdRoute,
  CapabilitiesSystemsRoute: CapabilitiesSystemsRouteWithChildren,
  CapabilitiesIndexRoute: CapabilitiesIndexRoute,
}

const CapabilitiesRouteWithChildren = CapabilitiesRoute._addFileChildren(
  CapabilitiesRouteChildren,
)

interface KnowledgeRouteChildren {
  KnowledgeIdRoute: typeof KnowledgeIdRoute
  KnowledgeManualRoute: typeof KnowledgeManualRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeIdRoute: KnowledgeIdRoute,
  KnowledgeManualRoute: KnowledgeManualRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface RecommendationsRouteChildren {
  RecommendationsIdRoute: typeof RecommendationsIdRoute
  RecommendationsIndexRoute: typeof RecommendationsIndexRoute
}

const RecommendationsRouteChildren: RecommendationsRouteChildren = {
  RecommendationsIdRoute: RecommendationsIdRoute,
  RecommendationsIndexRoute: RecommendationsIndexRoute,
}

const RecommendationsRouteWithChildren = RecommendationsRoute._addFileChildren(
  RecommendationsRouteChildren,
)

interface SchedulerRouteChildren {
  SchedulerIdRoute: typeof SchedulerIdRoute
  SchedulerIndexRoute: typeof SchedulerIndexRoute
}

const SchedulerRouteChildren: SchedulerRouteChildren = {
  SchedulerIdRoute: SchedulerIdRoute,
  SchedulerIndexRoute: SchedulerIndexRoute,
}

const SchedulerRouteWithChildren = SchedulerRoute._addFileChildren(
  SchedulerRouteChildren,
)

interface SeoRunsRouteChildren {
  SeoRunsIdRoute: typeof SeoRunsIdRoute
  SeoRunsIndexRoute: typeof SeoRunsIndexRoute
}

const SeoRunsRouteChildren: SeoRunsRouteChildren = {
  SeoRunsIdRoute: SeoRunsIdRoute,
  SeoRunsIndexRoute: SeoRunsIndexRoute,
}

const SeoRunsRouteWithChildren =
  SeoRunsRoute._addFileChildren(SeoRunsRouteChildren)

interface WorkflowsRouteChildren {
  WorkflowsIdRoute: typeof WorkflowsIdRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsIdRoute: WorkflowsIdRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ApprovalsRoute: ApprovalsRoute,
  AskRoute: AskRoute,
  AssetsRoute: AssetsRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AuthorityRoute: AuthorityRoute,
  CapabilitiesRoute: CapabilitiesRouteWithChildren,
  CommandCenterRoute: CommandCenterRoute,
  CompetitorsRoute: CompetitorsRoute,
  EssentialsRoute: EssentialsRoute,
  Ga4Route: Ga4Route,
  GapsRoute: GapsRoute,
  KeywordsRoute: KeywordsRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  McpRoute: McpRoute,
  MeasurementRoute: MeasurementRoute,
  NotesRoute: NotesRoute,
  OpenaiAdsRoute: OpenaiAdsRoute,
  OpenseoRoute: OpenseoRoute,
  OperatorsRoute: OperatorsRoute,
  RecommendationsRoute: RecommendationsRouteWithChildren,
  RoadmapRoute: RoadmapRoute,
  SchedulerRoute: SchedulerRouteWithChildren,
  SeoRunsRoute: SeoRunsRouteWithChildren,
  SpendRoute: SpendRoute,
  StudioRoute: StudioRoute,
  TodayRoute: TodayRoute,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdsAdvertisersRoute: AdsAdvertisersRoute,
  ApiAgentChatRoute: ApiAgentChatRoute,
  ApiStudioChatRoute: ApiStudioChatRoute,
  ChangesIdRoute: ChangesIdRoute,
  PagesToolsRoute: PagesToolsRoute,
  SearchToolsRoute: SearchToolsRoute,
  AdsIndexRoute: AdsIndexRoute,
  ChangesIndexRoute: ChangesIndexRoute,
  PagesIndexRoute: PagesIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksDataforseoPostbackRoute: ApiPublicHooksDataforseoPostbackRoute,
  ApiPublicHooksOpenaiAdsConversionsRoute:
    ApiPublicHooksOpenaiAdsConversionsRoute,
  ApiPublicHooksOpenaiAdsEventsRoute: ApiPublicHooksOpenaiAdsEventsRoute,
  ApiPublicHooksProposeFromEvidenceRoute:
    ApiPublicHooksProposeFromEvidenceRoute,
  ApiPublicHooksSchedulerTickRoute: ApiPublicHooksSchedulerTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
