-- Tool estate catalog: typed aliases + reproducible source-controlled seed.
ALTER TABLE public.tool_aliases
  ADD COLUMN IF NOT EXISTS alias_kind text NOT NULL DEFAULT 'other';

ALTER TABLE public.tool_aliases DROP CONSTRAINT IF EXISTS tool_aliases_alias_kind_check;
ALTER TABLE public.tool_aliases ADD CONSTRAINT tool_aliases_alias_kind_check
  CHECK (alias_kind = ANY (ARRAY['included_service','duplicate_registration','adapter_alias','client_alias','other']));

-- Canonical AOOS tool estate catalog. Stable keys only. No tenant ids, no credential values.
CREATE OR REPLACE FUNCTION public.seed_tool_estate_for_tenant(target_tenant uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $seed$
BEGIN
  IF target_tenant IS NULL THEN RETURN; END IF;

  INSERT INTO public.tool_systems (tenant_id, stable_key, name, kind, provider, version, execution_location, discovered_from, installed_state, credential_state, verification_state, aoos_connection_state, last_verified_at, source_reference, summary, metadata, is_essential, available_state, enabled_state, implemented_state, visible_in_aoos) VALUES
  (target_tenant, 'api.anthropic', 'Anthropic', 'api', 'Anthropic', NULL, 'remote', 'Vault metadata snapshot 2026-08-11', 'not_installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'https://docs.anthropic.com/', 'Safe credential metadata exists. Nothing in AOOS calls it today.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.chrome_ux_report', 'Chrome UX Report', 'api', 'Google', NULL, 'remote', 'Vault metadata snapshot 2026-08-11', 'not_installed', 'unknown', 'surface_counted', 'not_connected', '2026-08-11', 'https://developer.chrome.com/docs/crux/api', 'Real world field performance data for a site. Provider surface counted only. Full normalized import queued.', '{}'::jsonb, true, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.dataforseo_v3', 'DataForSEO API v3', 'api', 'DataForSEO', 'v3', 'remote', 'Official OpenAPI snapshot 2026-08-11', 'not_installed', 'configured', 'surface_counted', 'callable', '2026-08-11', 'https://docs.dataforseo.com/v3/', 'Full provider surface counted from the official OpenAPI snapshot: 453 paths and 570 operations across 12 families. AOOS implements only a small subset today. Full normalized import queued.', '{"paths": 453, "families": 12, "operations": 570}'::jsonb, true, 'available_to_enable', 'enabled', 'partially_implemented', true),
  (target_tenant, 'api.firecrawl', 'Firecrawl', 'api', 'Firecrawl', NULL, 'remote', 'Vault metadata snapshot 2026-08-11', 'not_installed', 'configured', 'live_proven', 'callable', '2026-08-11', 'https://docs.firecrawl.dev/', 'Crawling and scraping provider. Safe credential metadata exists, AOOS research already calls it, and calls are live proven.', '{}'::jsonb, true, 'available_to_enable', 'enabled', 'implemented', true),
  (target_tenant, 'api.ga_admin', 'Google Analytics Admin API', 'api', 'Google', 'v1beta + v1alpha', 'remote', 'Discovery document 2026-08-11', 'not_installed', 'configured', 'surface_counted', 'not_connected', '2026-08-11', 'https://developers.google.com/analytics/devguides/config/admin/v1', '55 v1beta methods and 166 v1alpha methods counted. Full normalized import queued.', '{"v1beta_methods": 55, "vault_evidence": {"proves": ["OAuth configuration observed"], "checked_on": "2026-08-11", "does_not_prove": ["API enabled", "implemented in AOOS", "callable from AOOS"]}, "v1alpha_methods": 166}'::jsonb, true, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.ga4_data', 'GA4 Data API', 'api', 'Google', 'v1beta', 'remote', 'Discovery document 2026-08-11', 'not_installed', 'configured', 'surface_counted', 'not_connected', '2026-08-11', 'https://developers.google.com/analytics/devguides/reporting/data/v1', '11 methods counted from the discovery document. Full normalized import queued.', '{"methods": 11, "vault_evidence": {"proves": ["OAuth configuration observed"], "checked_on": "2026-08-11", "does_not_prove": ["API enabled", "implemented in AOOS", "callable from AOOS"]}}'::jsonb, true, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.gemini', 'Gemini', 'api', 'Google', NULL, 'remote', 'Vault metadata snapshot 2026-08-11', 'not_installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'https://ai.google.dev/gemini-api/docs', 'Safe credential metadata exists. Nothing in AOOS calls it today.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.google_ads_v25', 'Google Ads API', 'api', 'Google', 'v25', 'remote', 'Official service list 2026-08-11', 'not_installed', 'configured', 'surface_counted', 'not_connected', '2026-08-11', 'https://developers.google.com/google-ads/api/', '110 services counted. The AOOS registry does not represent the full surface. Full normalized import queued.', '{"services": 110, "vault_evidence": {"proves": ["OAuth configuration observed", "Google Ads developer token observed"], "checked_on": "2026-08-11", "does_not_prove": ["API enabled", "account linked", "implemented in AOOS", "callable from AOOS"]}}'::jsonb, true, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.google_tag_manager', 'Google Tag Manager API', 'api', 'Google', 'v2', 'remote', 'Official documentation 2026-08-11', 'not_installed', 'configured', 'surface_counted', 'not_connected', '2026-08-11', 'https://developers.google.com/tag-platform/tag-manager/api/v2', 'Provider surface counted. Full normalized import queued.', '{"vault_evidence": {"proves": ["OAuth configuration observed"], "checked_on": "2026-08-11", "does_not_prove": ["API enabled", "implemented in AOOS", "callable from AOOS"]}}'::jsonb, true, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.granot', 'Granot', 'api', 'Granot', NULL, 'remote', 'Vault metadata snapshot 2026-08-11', 'not_installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Vendor documentation, not public', 'Moving operations system. Safe credential metadata exists. Nothing in AOOS calls it today.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.hermes', 'Hermes', 'api', 'Hermes', NULL, 'remote', 'Vault metadata snapshot 2026-08-11', 'not_installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Vendor documentation, not public', 'Safe credential metadata exists. Nothing in AOOS calls it today.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.hyperfx', 'HyperFX', 'api', 'HyperFX', NULL, 'remote', 'Vault metadata snapshot 2026-08-11', 'not_installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Vendor documentation, not public', 'Safe credential metadata exists. Nothing in AOOS calls it today.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.marky', 'Marky', 'api', 'Marky', NULL, 'remote', 'Vault metadata snapshot 2026-08-11', 'not_installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Vendor documentation, not public', 'Safe credential metadata exists. Nothing in AOOS calls it today.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.meta', 'Meta', 'api', 'Meta', NULL, 'remote', 'Vault metadata snapshot 2026-08-11', 'not_installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'https://developers.facebook.com/docs/marketing-apis/', 'Safe credential metadata exists. Nothing in AOOS calls it today.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.openai', 'OpenAI', 'api', 'OpenAI', NULL, 'remote', 'Vault metadata snapshot 2026-08-11', 'not_installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'https://platform.openai.com/docs', 'Safe credential metadata exists. Nothing in AOOS calls it today.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.pagespeed_insights', 'PageSpeed Insights', 'api', 'Google', 'v5', 'remote', 'Official documentation 2026-08-11', 'not_installed', 'unknown', 'surface_counted', 'not_connected', '2026-08-11', 'https://developers.google.com/speed/docs/insights/v5/get-started', 'Provider surface counted. Full normalized import queued.', '{}'::jsonb, true, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.perplexity', 'Perplexity', 'api', 'Perplexity', NULL, 'remote', 'Vault metadata snapshot 2026-08-11', 'not_installed', 'configured', 'live_proven', 'callable', '2026-08-11', 'https://docs.perplexity.ai/', 'Answer engine used by AOOS research. Safe credential metadata exists and calls are live proven.', '{}'::jsonb, false, 'available_to_enable', 'enabled', 'implemented', true),
  (target_tenant, 'api.resend', 'Resend', 'api', 'Resend', NULL, 'remote', 'Vault metadata snapshot 2026-08-11', 'not_installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'https://resend.com/docs', 'Email delivery provider. Safe credential metadata exists. Nothing in AOOS calls it today.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'api.search_console', 'Google Search Console API', 'api', 'Google', 'v1', 'remote', 'Official documentation 2026-08-11', 'not_installed', 'configured', 'surface_counted', 'callable', '2026-08-11', 'https://developers.google.com/webmaster-tools/v1/api_reference_index', 'Four families counted: Search Analytics, Sitemaps, Sites, and URL Inspection. AOOS already reads a live subset. Full normalized import queued.', '{"families": ["Search Analytics", "Sitemaps", "Sites", "URL Inspection"], "vault_evidence": {"proves": ["OAuth configuration observed"], "checked_on": "2026-08-11", "does_not_prove": ["API enabled", "implemented in AOOS", "callable from AOOS"]}}'::jsonb, true, 'available_to_enable', 'enabled', 'partially_implemented', true),
  (target_tenant, 'api.slicktext', 'SlickText', 'api', 'SlickText', NULL, 'remote', 'Vault metadata snapshot 2026-08-11', 'not_installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'https://api.slicktext.com/docs/v1/', 'Messaging provider. Safe credential metadata exists. Nothing in AOOS calls it today.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.apify_mcp', 'Composio: apify_mcp', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio. The connection was observed but the system was not individually proven working in this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.browseai', 'Composio: browseai', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio. The connection was observed but the system was not individually proven working in this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.dataforseo', 'Composio: dataforseo', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'live_proven', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio and individually proven working during this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.elevenlabs', 'Composio: elevenlabs', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio. The connection was observed but the system was not individually proven working in this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.firecrawl', 'Composio: firecrawl', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio. The connection was observed but the system was not individually proven working in this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.github', 'Composio: github', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio. The connection was observed but the system was not individually proven working in this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.gmail', 'Composio: gmail', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio. The connection was observed but the system was not individually proven working in this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.google_analytics', 'Composio: google_analytics', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'live_proven', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio and individually proven working during this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.google_search_console', 'Composio: google_search_console', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio. The connection was observed but the system was not individually proven working in this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.googleads', 'Composio: googleads', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'live_proven', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio and individually proven working during this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.googledrive', 'Composio: googledrive', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio. The connection was observed but the system was not individually proven working in this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.googlesuper', 'Composio: googlesuper', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio. The connection was observed but the system was not individually proven working in this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.linear', 'Composio: linear', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio. The connection was observed but the system was not individually proven working in this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.perplexityai', 'Composio: perplexityai', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio. The connection was observed but the system was not individually proven working in this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.supabase', 'Composio: supabase', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio. The connection was observed but the system was not individually proven working in this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.veo', 'Composio: veo', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio. The connection was observed but the system was not individually proven working in this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'composio.vercel', 'Composio: vercel', 'connector', 'Composio', NULL, 'remote', 'Composio connected systems 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Composio connection list', 'Manually connected in Composio. The connection was observed but the system was not individually proven working in this audit. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'lovable.n8n', 'n8n', 'connector', 'n8n', NULL, 'cloud', 'Lovable workspace registrations 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Lovable workspace connection', 'One n8n endpoint, registered three times. Counted once here, with the three registrations kept as aliases.', '{"duplicate_registrations": 3}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'lovable.notion', 'Notion', 'connector', 'Notion', NULL, 'cloud', 'Lovable workspace registrations 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Lovable workspace connection', 'Connected in the Lovable workspace. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'lovable.truenoll', 'TruEnoll', 'connector', 'Lovable workspace', NULL, 'cloud', 'Lovable workspace registrations 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Lovable workspace connection', 'Connected in the Lovable workspace. No AOOS bridge yet.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'lovable.trumove_website_final', 'TruMove Website Final', 'connector', 'Lovable workspace', NULL, 'cloud', 'Lovable workspace registrations 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Lovable workspace connection', 'Connected in the Lovable workspace and exposes three tools. No AOOS bridge yet.', '{"tool_count": 3}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.adloop', 'AdLoop', 'local_app', 'AdLoop', '0.13.0', 'local', 'Local workstation audit 2026-08-11', 'installed', 'configured', 'live_proven', 'not_connected', '2026-08-11', 'Local project: adloop', 'Google Ads, Analytics, Search Console, and Tag Manager control surface. Installed, configured, and proven working on the local workstation. AOOS cloud has no bridge to it yet.', '{"safety": {"plan_first": true, "pending_plans": "process memory scoped", "require_dry_run": true, "confirm_and_apply_defaults_dry_run": true}, "mcp_tool_count": 67}'::jsonb, true, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.codebase_memory_mcp', 'codebase-memory-mcp', 'mcp', NULL, NULL, 'local', 'Local Codex MCP registrations 2026-08-11', 'installed', 'unknown', 'unverified', 'not_connected', '2026-08-11', 'Local MCP client registration', 'Local MCP registration observed. Not callable from AOOS.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.composio_platform', 'Composio', 'connector', 'Composio', NULL, 'remote', 'Local client registrations 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Local MCP client registration', 'Composio connector platform registered with local AI clients.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.dataforseo_live_adapter', 'DataForSEO Live adapter', 'adapter', 'DataForSEO', NULL, 'local', 'Local workstation audit 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Local project: trumove-marketing-platform', 'A small local wrapper over the one existing paid DataForSEO account. Not a separate provider or account, and not callable from AOOS.', '{"shares_account_with": "api.dataforseo_v3"}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.firecrawl_live', 'Firecrawl Live adapter', 'adapter', 'Firecrawl', NULL, 'local', 'Local workstation audit 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Local project: trumove-marketing-platform', 'Local adapter around Firecrawl crawling, scraping, and monitoring. Not callable from AOOS.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.github_mcp', 'GitHub', 'mcp', 'GitHub', NULL, 'remote', 'Local Claude MCP registrations 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Local MCP client registration', 'Registered with a local AI client. Not callable from AOOS.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.google_ads_mcp', 'Google Ads MCP', 'mcp', 'Google', '0.0.1', 'local', 'Local workstation audit 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'google-ads 31.2.0', 'Official local Google Ads MCP package. Read only. Not callable from AOOS.', '{"library": "google-ads 31.2.0", "read_only": true}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.google_analytics_mcp', 'Google Analytics MCP', 'mcp', 'Google', '0.6.0', 'local', 'Local workstation audit 2026-08-11', 'installed', 'configured', 'live_proven', 'not_connected', '2026-08-11', 'Official Google Analytics MCP package', 'Official local Google Analytics MCP package. Proven working locally. Not callable from AOOS.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.google_live_adapter', 'Google Live adapter', 'adapter', 'Google', NULL, 'local', 'Local workstation audit 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Local project: trumove-marketing-platform', 'Local adapter for Search Console, Analytics, and Ads reads. Not callable from AOOS.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.lovable_mcp', 'Lovable', 'mcp', 'Lovable', NULL, 'remote', 'Local Codex and Claude MCP registrations 2026-08-11', 'installed', 'unknown', 'unverified', 'not_connected', '2026-08-11', 'Local MCP client registration', 'Registered with two local AI clients under the names Lovable and lovery. Not callable from AOOS.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.marketing_yolo_vault', 'Credential vault (metadata only)', 'vault', NULL, NULL, 'remote', 'Vault metadata snapshot 2026-08-11', 'not_installed', 'configured', 'live_proven', 'not_connected', '2026-08-11', 'Safe metadata enumeration only', '25 metadata records checked · 20 active records mapped to 16 providers · secret values never copied.', '{"note": "Aggregate only. No credential names, labels, accounts, hosts, paths, or values are stored.", "records_checked": 25, "providers_mapped": 16, "secret_values_copied": false, "active_records_mapped": 20}'::jsonb, false, 'not_available', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.mem0rize', 'mem0rize', 'mcp', NULL, NULL, 'remote', 'Local Codex and Claude MCP registrations 2026-08-11', 'installed', 'unknown', 'unverified', 'not_connected', '2026-08-11', 'Local MCP client registration', 'Registered with two local AI clients. Not callable from AOOS.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.node_repl', 'node_repl', 'mcp', NULL, NULL, 'local', 'Local Codex MCP registrations 2026-08-11', 'installed', 'unknown', 'unverified', 'not_connected', '2026-08-11', 'Local MCP client registration', 'Local MCP registration observed. Not callable from AOOS.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.openrouter', 'OpenRouter', 'mcp', 'OpenRouter', NULL, 'remote', 'Local Codex and Claude MCP registrations 2026-08-11', 'installed', 'configured', 'unverified', 'not_connected', '2026-08-11', 'Local MCP client registration', 'Registered with two local AI clients. Not callable from AOOS.', '{}'::jsonb, false, 'unknown', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.openseo', 'OpenSEO', 'repository', 'every-app/open-seo', '0.1.2', 'local', 'Local workstation audit 2026-08-11', 'installed', 'configured', 'partially_live_proven', 'not_connected', '2026-07-27', 'Upstream: every-app/open-seo', 'SEO research and audit toolkit installed as a local repository. 22 of 24 operations were proven working locally on 2026-07-27.', '{"not_proven": ["getSearchConsolePerformance", "inspectUrls"], "live_proven": "22/24"}'::jsonb, true, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.sequential_thinking', 'sequential-thinking', 'mcp', NULL, NULL, 'local', 'Local Codex and Claude MCP registrations 2026-08-11', 'installed', 'unknown', 'unverified', 'not_connected', '2026-08-11', 'Local MCP client registration', 'Registered with two local AI clients. Not callable from AOOS.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true),
  (target_tenant, 'sys.trumove_communications', 'trumove-communications', 'mcp', NULL, NULL, 'local', 'Local Codex MCP registrations 2026-08-11', 'installed', 'unknown', 'unverified', 'not_connected', '2026-08-11', 'Local MCP client registration', 'Local MCP registration observed. Not callable from AOOS.', '{}'::jsonb, false, 'available_to_enable', 'unknown', 'not_implemented', true)
  ON CONFLICT (tenant_id, stable_key) DO NOTHING;

  INSERT INTO public.tool_operations (tenant_id, system_id, operation_key, display_name, operation_mode, mutates_external_state, cost_model, http_method, mcp_tool_name, notes, source_reference, metadata)
  SELECT target_tenant, s.id, c.operation_key, c.display_name, c.operation_mode, c.mutates_external_state, c.cost_model, c.http_method, c.mcp_tool_name, c.notes, c.source_reference, c.metadata
  FROM (VALUES
    ('sys.adloop', 'add_negative_keywords', 'add_negative_keywords', 'draft', false, 'provider_quota', NULL, 'add_negative_keywords', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'add_negative_locations', 'add_negative_locations', 'draft', false, 'provider_quota', NULL, 'add_negative_locations', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'add_to_negative_keyword_list', 'add_to_negative_keyword_list', 'draft', false, 'provider_quota', NULL, 'add_to_negative_keyword_list', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'analyze_campaign_conversions', 'analyze_campaign_conversions', 'read', false, 'provider_quota', NULL, 'analyze_campaign_conversions', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'analyze_page_speed', 'analyze_page_speed', 'read', false, 'provider_quota', NULL, 'analyze_page_speed', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'attach_shared_set_to_campaigns', 'attach_shared_set_to_campaigns', 'draft', false, 'provider_quota', NULL, 'attach_shared_set_to_campaigns', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'attribution_check', 'attribution_check', 'read', false, 'provider_quota', NULL, 'attribution_check', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'audit_event_coverage', 'audit_event_coverage', 'read', false, 'provider_quota', NULL, 'audit_event_coverage', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'confirm_and_apply', 'confirm_and_apply', 'write', true, 'provider_quota', NULL, 'confirm_and_apply', 'Write gated. The only operation that can change anything outside AOOS, and it defaults to a dry run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'detach_shared_set_from_campaigns', 'detach_shared_set_from_campaigns', 'draft', false, 'provider_quota', NULL, 'detach_shared_set_from_campaigns', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'discover_keywords', 'discover_keywords', 'read', false, 'provider_quota', NULL, 'discover_keywords', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'draft_ad_group', 'draft_ad_group', 'draft', false, 'provider_quota', NULL, 'draft_ad_group', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'draft_callouts', 'draft_callouts', 'draft', false, 'provider_quota', NULL, 'draft_callouts', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'draft_campaign', 'draft_campaign', 'draft', false, 'provider_quota', NULL, 'draft_campaign', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'draft_demographic_targeting', 'draft_demographic_targeting', 'draft', false, 'provider_quota', NULL, 'draft_demographic_targeting', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'draft_image_assets', 'draft_image_assets', 'draft', false, 'provider_quota', NULL, 'draft_image_assets', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'draft_key_event', 'draft_key_event', 'draft', false, 'provider_quota', NULL, 'draft_key_event', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'draft_keywords', 'draft_keywords', 'draft', false, 'provider_quota', NULL, 'draft_keywords', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'draft_responsive_search_ad', 'draft_responsive_search_ad', 'draft', false, 'provider_quota', NULL, 'draft_responsive_search_ad', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'draft_sitelinks', 'draft_sitelinks', 'draft', false, 'provider_quota', NULL, 'draft_sitelinks', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'draft_structured_snippets', 'draft_structured_snippets', 'draft', false, 'provider_quota', NULL, 'draft_structured_snippets', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'enable_entity', 'enable_entity', 'draft', false, 'provider_quota', NULL, 'enable_entity', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'estimate_budget', 'estimate_budget', 'read', false, 'provider_quota', NULL, 'estimate_budget', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'generate_tracking_code', 'generate_tracking_code', 'draft', false, 'provider_quota', NULL, 'generate_tracking_code', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_account_summaries', 'get_account_summaries', 'read', false, 'provider_quota', NULL, 'get_account_summaries', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_ad_performance', 'get_ad_performance', 'read', false, 'provider_quota', NULL, 'get_ad_performance', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_asset_performance', 'get_asset_performance', 'read', false, 'provider_quota', NULL, 'get_asset_performance', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_audience_performance', 'get_audience_performance', 'read', false, 'provider_quota', NULL, 'get_audience_performance', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_campaign_performance', 'get_campaign_performance', 'read', false, 'provider_quota', NULL, 'get_campaign_performance', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_demographic_targeting', 'get_demographic_targeting', 'read', false, 'provider_quota', NULL, 'get_demographic_targeting', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_detailed_asset_performance', 'get_detailed_asset_performance', 'read', false, 'provider_quota', NULL, 'get_detailed_asset_performance', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_gtm_tag', 'get_gtm_tag', 'read', false, 'provider_quota', NULL, 'get_gtm_tag', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_gtm_trigger', 'get_gtm_trigger', 'read', false, 'provider_quota', NULL, 'get_gtm_trigger', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_gtm_version', 'get_gtm_version', 'read', false, 'provider_quota', NULL, 'get_gtm_version', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_gtm_workspace_diff', 'get_gtm_workspace_diff', 'read', false, 'provider_quota', NULL, 'get_gtm_workspace_diff', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_keyword_performance', 'get_keyword_performance', 'read', false, 'provider_quota', NULL, 'get_keyword_performance', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_merchant_feed_health', 'get_merchant_feed_health', 'read', false, 'provider_quota', NULL, 'get_merchant_feed_health', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_negative_keyword_list_campaigns', 'get_negative_keyword_list_campaigns', 'read', false, 'provider_quota', NULL, 'get_negative_keyword_list_campaigns', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_negative_keyword_list_keywords', 'get_negative_keyword_list_keywords', 'read', false, 'provider_quota', NULL, 'get_negative_keyword_list_keywords', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_negative_keyword_lists', 'get_negative_keyword_lists', 'read', false, 'provider_quota', NULL, 'get_negative_keyword_lists', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_negative_keywords', 'get_negative_keywords', 'read', false, 'provider_quota', NULL, 'get_negative_keywords', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_pmax_performance', 'get_pmax_performance', 'read', false, 'provider_quota', NULL, 'get_pmax_performance', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_recommendations', 'get_recommendations', 'read', false, 'provider_quota', NULL, 'get_recommendations', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_search_terms', 'get_search_terms', 'read', false, 'provider_quota', NULL, 'get_search_terms', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'get_tracking_events', 'get_tracking_events', 'read', false, 'provider_quota', NULL, 'get_tracking_events', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'health_check', 'health_check', 'read', false, 'provider_quota', NULL, 'health_check', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'landing_page_analysis', 'landing_page_analysis', 'read', false, 'provider_quota', NULL, 'landing_page_analysis', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'list_accounts', 'list_accounts', 'read', false, 'provider_quota', NULL, 'list_accounts', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'list_gsc_sites', 'list_gsc_sites', 'read', false, 'provider_quota', NULL, 'list_gsc_sites', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'list_gtm_accounts', 'list_gtm_accounts', 'read', false, 'provider_quota', NULL, 'list_gtm_accounts', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'list_gtm_containers', 'list_gtm_containers', 'read', false, 'provider_quota', NULL, 'list_gtm_containers', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'list_gtm_tags', 'list_gtm_tags', 'read', false, 'provider_quota', NULL, 'list_gtm_tags', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'list_gtm_triggers', 'list_gtm_triggers', 'read', false, 'provider_quota', NULL, 'list_gtm_triggers', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'list_gtm_variables', 'list_gtm_variables', 'read', false, 'provider_quota', NULL, 'list_gtm_variables', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'list_gtm_versions', 'list_gtm_versions', 'read', false, 'provider_quota', NULL, 'list_gtm_versions', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'list_gtm_workspaces', 'list_gtm_workspaces', 'read', false, 'provider_quota', NULL, 'list_gtm_workspaces', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'list_merchant_accounts', 'list_merchant_accounts', 'read', false, 'provider_quota', NULL, 'list_merchant_accounts', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'pause_entity', 'pause_entity', 'draft', false, 'provider_quota', NULL, 'pause_entity', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'propose_negative_keyword_list', 'propose_negative_keyword_list', 'draft', false, 'provider_quota', NULL, 'propose_negative_keyword_list', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'remove_entity', 'remove_entity', 'draft', false, 'provider_quota', NULL, 'remove_entity', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'run_ga4_report', 'run_ga4_report', 'read', false, 'provider_quota', NULL, 'run_ga4_report', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'run_gaql', 'run_gaql', 'read', false, 'provider_quota', NULL, 'run_gaql', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'run_gsc_report', 'run_gsc_report', 'read', false, 'provider_quota', NULL, 'run_gsc_report', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'run_realtime_report', 'run_realtime_report', 'read', false, 'provider_quota', NULL, 'run_realtime_report', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.adloop', 'update_ad_group', 'update_ad_group', 'draft', false, 'provider_quota', NULL, 'update_ad_group', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'update_campaign', 'update_campaign', 'draft', false, 'provider_quota', NULL, 'update_campaign', 'Prepares a plan or a local artifact. Nothing outside AOOS changes until confirm_and_apply is run.', NULL, '{}'::jsonb),
    ('sys.adloop', 'validate_tracking', 'validate_tracking', 'read', false, 'provider_quota', NULL, 'validate_tracking', 'Reads data only. Nothing outside AOOS changes.', NULL, '{}'::jsonb),
    ('sys.dataforseo_live_adapter', 'fetchBacklinksSummary', 'fetchBacklinksSummary', 'read', false, 'metered', NULL, 'fetchBacklinksSummary', NULL, NULL, '{}'::jsonb),
    ('sys.dataforseo_live_adapter', 'fetchDomainRankOverview', 'fetchDomainRankOverview', 'read', false, 'metered', NULL, 'fetchDomainRankOverview', NULL, NULL, '{}'::jsonb),
    ('sys.dataforseo_live_adapter', 'fetchKeywordIdeas', 'fetchKeywordIdeas', 'read', false, 'metered', NULL, 'fetchKeywordIdeas', NULL, NULL, '{}'::jsonb),
    ('sys.dataforseo_live_adapter', 'fetchOnPageInstantAudit', 'fetchOnPageInstantAudit', 'read', false, 'metered', NULL, 'fetchOnPageInstantAudit', NULL, NULL, '{}'::jsonb),
    ('sys.dataforseo_live_adapter', 'fetchRankedKeywords', 'fetchRankedKeywords', 'read', false, 'metered', NULL, 'fetchRankedKeywords', NULL, NULL, '{}'::jsonb),
    ('sys.dataforseo_live_adapter', 'fetchSearchVolume', 'fetchSearchVolume', 'read', false, 'metered', NULL, 'fetchSearchVolume', NULL, NULL, '{}'::jsonb),
    ('sys.dataforseo_live_adapter', 'fetchSerpOrganic', 'fetchSerpOrganic', 'read', false, 'metered', NULL, 'fetchSerpOrganic', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'cancelCrawl', 'cancelCrawl', 'draft', false, 'metered', NULL, 'cancelCrawl', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'createMonitor', 'createMonitor', 'draft', false, 'metered', NULL, 'createMonitor', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'deleteMonitor', 'deleteMonitor', 'draft', false, 'metered', NULL, 'deleteMonitor', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'getBatchScrapeStatus', 'getBatchScrapeStatus', 'read', false, 'free', NULL, 'getBatchScrapeStatus', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'getCrawlErrors', 'getCrawlErrors', 'read', false, 'free', NULL, 'getCrawlErrors', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'getCrawlStatus', 'getCrawlStatus', 'read', false, 'free', NULL, 'getCrawlStatus', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'getCreditUsage', 'getCreditUsage', 'read', false, 'free', NULL, 'getCreditUsage', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'getMonitor', 'getMonitor', 'read', false, 'free', NULL, 'getMonitor', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'getMonitorCheck', 'getMonitorCheck', 'read', false, 'free', NULL, 'getMonitorCheck', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'listActiveCrawls', 'listActiveCrawls', 'read', false, 'free', NULL, 'listActiveCrawls', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'listMonitorChecks', 'listMonitorChecks', 'read', false, 'free', NULL, 'listMonitorChecks', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'listMonitors', 'listMonitors', 'read', false, 'free', NULL, 'listMonitors', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'mapUrls', 'mapUrls', 'read', false, 'metered', NULL, 'mapUrls', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'parseFile', 'parseFile', 'read', false, 'metered', NULL, 'parseFile', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'runMonitor', 'runMonitor', 'draft', false, 'metered', NULL, 'runMonitor', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'scrapeUrl', 'scrapeUrl', 'read', false, 'metered', NULL, 'scrapeUrl', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'searchWeb', 'searchWeb', 'read', false, 'metered', NULL, 'searchWeb', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'startBatchScrape', 'startBatchScrape', 'draft', false, 'metered', NULL, 'startBatchScrape', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'startCrawl', 'startCrawl', 'draft', false, 'metered', NULL, 'startCrawl', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'updateMonitor', 'updateMonitor', 'draft', false, 'metered', NULL, 'updateMonitor', NULL, NULL, '{}'::jsonb),
    ('sys.firecrawl_live', 'waitForJob', 'waitForJob', 'read', false, 'free', NULL, 'waitForJob', NULL, NULL, '{}'::jsonb),
    ('sys.google_ads_mcp', 'customers_list_accessible_customers', 'customers_list_accessible_customers', 'read', false, 'provider_quota', NULL, 'customers_list_accessible_customers', NULL, NULL, '{}'::jsonb),
    ('sys.google_ads_mcp', 'metadata_get_resource_metadata', 'metadata_get_resource_metadata', 'read', false, 'provider_quota', NULL, 'metadata_get_resource_metadata', NULL, NULL, '{}'::jsonb),
    ('sys.google_ads_mcp', 'search_search', 'search_search', 'read', false, 'provider_quota', NULL, 'search_search', 'Runs an arbitrary GAQL query. Read only.', NULL, '{}'::jsonb),
    ('sys.google_analytics_mcp', 'get_account_summaries', 'get_account_summaries', 'read', false, 'provider_quota', NULL, 'get_account_summaries', NULL, NULL, '{}'::jsonb),
    ('sys.google_analytics_mcp', 'get_custom_dimensions_and_metrics', 'get_custom_dimensions_and_metrics', 'read', false, 'provider_quota', NULL, 'get_custom_dimensions_and_metrics', NULL, NULL, '{}'::jsonb),
    ('sys.google_analytics_mcp', 'get_date_ranges_hints', 'get_date_ranges_hints', 'internal', false, 'free', NULL, 'get_date_ranges_hints', 'Helper operation. Returns guidance for building a request.', NULL, '{}'::jsonb),
    ('sys.google_analytics_mcp', 'get_dimension_filter_hints', 'get_dimension_filter_hints', 'internal', false, 'free', NULL, 'get_dimension_filter_hints', 'Helper operation. Returns guidance for building a request.', NULL, '{}'::jsonb),
    ('sys.google_analytics_mcp', 'get_funnel_steps_hints', 'get_funnel_steps_hints', 'internal', false, 'free', NULL, 'get_funnel_steps_hints', 'Helper operation. Returns guidance for building a request.', NULL, '{}'::jsonb),
    ('sys.google_analytics_mcp', 'get_metric_filter_hints', 'get_metric_filter_hints', 'internal', false, 'free', NULL, 'get_metric_filter_hints', 'Helper operation. Returns guidance for building a request.', NULL, '{}'::jsonb),
    ('sys.google_analytics_mcp', 'get_order_bys_hints', 'get_order_bys_hints', 'internal', false, 'free', NULL, 'get_order_bys_hints', 'Helper operation. Returns guidance for building a request.', NULL, '{}'::jsonb),
    ('sys.google_analytics_mcp', 'get_property_details', 'get_property_details', 'read', false, 'provider_quota', NULL, 'get_property_details', NULL, NULL, '{}'::jsonb),
    ('sys.google_analytics_mcp', 'list_google_ads_links', 'list_google_ads_links', 'read', false, 'provider_quota', NULL, 'list_google_ads_links', NULL, NULL, '{}'::jsonb),
    ('sys.google_analytics_mcp', 'list_property_annotations', 'list_property_annotations', 'read', false, 'provider_quota', NULL, 'list_property_annotations', NULL, NULL, '{}'::jsonb),
    ('sys.google_analytics_mcp', 'run_conversions_report', 'run_conversions_report', 'read', false, 'provider_quota', NULL, 'run_conversions_report', NULL, NULL, '{}'::jsonb),
    ('sys.google_analytics_mcp', 'run_funnel_report', 'run_funnel_report', 'read', false, 'provider_quota', NULL, 'run_funnel_report', NULL, NULL, '{}'::jsonb),
    ('sys.google_analytics_mcp', 'run_realtime_report', 'run_realtime_report', 'read', false, 'provider_quota', NULL, 'run_realtime_report', NULL, NULL, '{}'::jsonb),
    ('sys.google_analytics_mcp', 'run_report', 'run_report', 'read', false, 'provider_quota', NULL, 'run_report', NULL, NULL, '{}'::jsonb),
    ('sys.google_live_adapter', 'fetchAdsSearchTerms', 'fetchAdsSearchTerms', 'read', false, 'provider_quota', NULL, 'fetchAdsSearchTerms', NULL, NULL, '{}'::jsonb),
    ('sys.google_live_adapter', 'fetchGa4Report', 'fetchGa4Report', 'read', false, 'provider_quota', NULL, 'fetchGa4Report', NULL, NULL, '{}'::jsonb),
    ('sys.google_live_adapter', 'fetchGscDaily', 'fetchGscDaily', 'read', false, 'provider_quota', NULL, 'fetchGscDaily', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'createProject', 'createProject', 'draft', false, 'free', NULL, 'createProject', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'findSerpCompetitors', 'findSerpCompetitors', 'read', false, 'metered', NULL, 'findSerpCompetitors', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'getAuditIssues', 'getAuditIssues', 'read', false, 'free', NULL, 'getAuditIssues', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'getAuditPages', 'getAuditPages', 'read', false, 'free', NULL, 'getAuditPages', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'getAuditStatus', 'getAuditStatus', 'read', false, 'free', NULL, 'getAuditStatus', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'getBacklinksOverview', 'getBacklinksOverview', 'read', false, 'metered', NULL, 'getBacklinksOverview', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'getBacklinksProfile', 'getBacklinksProfile', 'read', false, 'metered', NULL, 'getBacklinksProfile', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'getDomainKeywordSuggestions', 'getDomainKeywordSuggestions', 'read', false, 'metered', NULL, 'getDomainKeywordSuggestions', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'getDomainOverview', 'getDomainOverview', 'read', false, 'metered', NULL, 'getDomainOverview', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'getGoogleBusinessQuestions', 'getGoogleBusinessQuestions', 'read', false, 'metered', NULL, 'getGoogleBusinessQuestions', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'getKeywordMetrics', 'getKeywordMetrics', 'read', false, 'metered', NULL, 'getKeywordMetrics', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'getLocalSerpResults', 'getLocalSerpResults', 'read', false, 'metered', NULL, 'getLocalSerpResults', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'getRankedKeywords', 'getRankedKeywords', 'read', false, 'free', NULL, 'getRankedKeywords', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'getRankTracker', 'getRankTracker', 'read', false, 'free', NULL, 'getRankTracker', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'getSearchConsolePerformance', 'getSearchConsolePerformance', 'read', false, 'free', NULL, 'getSearchConsolePerformance', 'Not proven working in the local instance on 2026-07-27. AOOS Search Console reads are independently live.', NULL, '{}'::jsonb),
    ('sys.openseo', 'getSerpResults', 'getSerpResults', 'read', false, 'metered', NULL, 'getSerpResults', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'inspectUrls', 'inspectUrls', 'read', false, 'free', NULL, 'inspectUrls', 'Not proven working in the local instance on 2026-07-27. AOOS Search Console reads are independently live.', NULL, '{}'::jsonb),
    ('sys.openseo', 'listProjects', 'listProjects', 'read', false, 'free', NULL, 'listProjects', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'listSavedKeywords', 'listSavedKeywords', 'read', false, 'free', NULL, 'listSavedKeywords', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'researchKeywords', 'researchKeywords', 'read', false, 'metered', NULL, 'researchKeywords', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'runSiteAudit', 'runSiteAudit', 'draft', false, 'unknown', NULL, 'runSiteAudit', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'saveKeywords', 'saveKeywords', 'draft', false, 'free', NULL, 'saveKeywords', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'searchLocalBusinesses', 'searchLocalBusinesses', 'read', false, 'metered', NULL, 'searchLocalBusinesses', NULL, NULL, '{}'::jsonb),
    ('sys.openseo', 'whoami', 'whoami', 'read', false, 'free', NULL, 'whoami', NULL, NULL, '{}'::jsonb)
  ) AS c(system_key, operation_key, display_name, operation_mode, mutates_external_state, cost_model, http_method, mcp_tool_name, notes, source_reference, metadata)
  JOIN public.tool_systems s ON s.tenant_id = target_tenant AND s.stable_key = c.system_key
  ON CONFLICT (tenant_id, system_id, operation_key) DO NOTHING;

  INSERT INTO public.tool_aliases (tenant_id, system_id, alias_key, alias_label, registered_in, note, alias_kind)
  SELECT target_tenant, s.id, c.alias_key, c.alias_label, c.registered_in, c.note, c.alias_kind
  FROM (VALUES
    ('sys.adloop', 'alias.adloop_live_wrapper', 'AdLoop Live wrapper', 'Local project: trumove-marketing-platform', 'A local adapter over canonical AdLoop, not a separate product.', 'adapter_alias'),
    ('sys.github_mcp', 'alias.claude_github', 'GitHub', 'Local Claude client', NULL, 'other'),
    ('sys.lovable_mcp', 'alias.claude_lovable', 'Lovable', 'Local Claude client', 'Cross client duplicate of the same system.', 'client_alias'),
    ('sys.mem0rize', 'alias.claude_mem0rize', 'mem0rize', 'Local Claude client', 'Cross client duplicate of the same system.', 'client_alias'),
    ('sys.openrouter', 'alias.claude_openrouter', 'openrouter', 'Local Claude client', 'Cross client duplicate of the same system.', 'client_alias'),
    ('sys.sequential_thinking', 'alias.claude_sequential_thinking', 'sequential-thinking', 'Local Claude client', 'Cross client duplicate of the same system.', 'client_alias'),
    ('sys.codebase_memory_mcp', 'alias.codex_codebase_memory', 'codebase-memory-mcp', 'Local Codex client', NULL, 'other'),
    ('sys.composio_platform', 'alias.codex_composio', 'composio', 'Local Codex client', NULL, 'other'),
    ('sys.composio_platform', 'alias.codex_composio_agent', 'composio-agent', 'Local Codex client', 'A second Composio registration in the same client.', 'duplicate_registration'),
    ('sys.lovable_mcp', 'alias.codex_lovable', 'Lovable / lovery', 'Local Codex client', NULL, 'client_alias'),
    ('sys.mem0rize', 'alias.codex_mem0rize', 'mem0rize', 'Local Codex client', NULL, 'client_alias'),
    ('sys.node_repl', 'alias.codex_node_repl', 'node_repl', 'Local Codex client', NULL, 'other'),
    ('sys.openrouter', 'alias.codex_openrouter', 'openrouter', 'Local Codex client', NULL, 'client_alias'),
    ('sys.sequential_thinking', 'alias.codex_sequential_thinking', 'sequential-thinking', 'Local Codex client', NULL, 'client_alias'),
    ('sys.trumove_communications', 'alias.codex_trumove_comms', 'trumove-communications', 'Local Codex client', NULL, 'other'),
    ('api.google_ads_v25', 'alias.google_keyword_planner', 'Keyword Planner', 'Google Ads API', 'Part of the Google Ads API, not a separate product.', 'included_service'),
    ('lovable.n8n', 'alias.lovable_n8n_1', 'n8n registration 1', 'Lovable workspace', 'Same endpoint as the other two registrations.', 'duplicate_registration'),
    ('lovable.n8n', 'alias.lovable_n8n_2', 'n8n registration 2', 'Lovable workspace', 'Same endpoint as the other two registrations.', 'duplicate_registration'),
    ('lovable.n8n', 'alias.lovable_n8n_3', 'n8n registration 3', 'Lovable workspace', 'Same endpoint as the other two registrations.', 'duplicate_registration'),
    ('sys.openseo', 'alias.openseo_ingestion', 'OpenSEO ingestion', 'Local project: trumove-marketing-platform', 'An ingestion adapter over canonical OpenSEO, not a separate product.', 'adapter_alias'),
    ('sys.openseo', 'alias.openseo_live_wrapper', 'OpenSEO Live wrapper', 'Local project: trumove-marketing-platform', 'A local adapter over canonical OpenSEO, not a separate product.', 'adapter_alias')
  ) AS c(system_key, alias_key, alias_label, registered_in, note, alias_kind)
  JOIN public.tool_systems s ON s.tenant_id = target_tenant AND s.stable_key = c.system_key
  ON CONFLICT (tenant_id, alias_key) DO UPDATE SET alias_kind = EXCLUDED.alias_kind;
END $seed$;

REVOKE ALL ON FUNCTION public.seed_tool_estate_for_tenant(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.seed_tool_estate_for_tenant(uuid) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.seed_tool_estate_for_tenant(uuid) TO service_role;

CREATE OR REPLACE FUNCTION public.seed_tool_estate_on_tenant_insert()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $trg$
BEGIN
  PERFORM public.seed_tool_estate_for_tenant(NEW.id);
  RETURN NEW;
END $trg$;

DROP TRIGGER IF EXISTS seed_tool_estate_after_tenant_insert ON public.tenants;
CREATE TRIGGER seed_tool_estate_after_tenant_insert
AFTER INSERT ON public.tenants
FOR EACH ROW EXECUTE FUNCTION public.seed_tool_estate_on_tenant_insert();

-- Reconcile every existing tenant with the source-controlled catalog.
DO $run$
DECLARE t uuid;
BEGIN
  FOR t IN SELECT id FROM public.tenants LOOP
    PERFORM public.seed_tool_estate_for_tenant(t);
  END LOOP;
END $run$;

-- Truthful live proof: the vault metadata index was reached and enumerated safely.
UPDATE public.tool_systems
   SET verification_state = 'live_proven'
 WHERE stable_key = 'sys.marketing_yolo_vault';